Update version to 9.4 for compilation
- Since > 2026/02/16 v9.1.0.183 checksum has been changed : install fails.
- Upstream versions >=9.1.0.183(2) <9.4: install fails 
npm ci --include=dev --prefix ./AdminPanel/client && npm --prefix ./AdminPanel/client run build
ERROR: "install:AdminPanel/server" exited with 1

- Upgrading to 9.4 fixes this issue